### ISSUE TITLE
guide-key for key bindings

### ISSUE THREAD

**Issue by narendraj9** [helpshift/emacs-up#1]
I think the guide-key extension can come in very handy when it comes to discovering new Emacs commands.  https://github.com/kai2nenobu/guide-key 

This is just a suggestion. :)

**Comment by vedang** [comment]
Hi @narendraj9 ,

I checked out `guide-key`, and it does not look like it adds much value over the built-in Emacs help system as described here: https://github.com/helpshift/emacs-up/blob/master/docs/01_opinionated_emacs_tutorial.org#helping-yourself

I plan to keep this setup as bare as possible, and encourage default Emacs behavior except where a package provides something that is just not possible in default Emacs (eg: `helm`)

Thanks for the suggestion, please reach out if there's anything else you feel should be part of this setup.
