### ISSUE TITLE
Seems to be broken

### ISSUE THREAD

**Issue by divs1210** [helpshift/emacs-up#4]
Hi!
I've been a long time user of your config. :)
Unfortunately, it is broken at the moment.
Everything works when emacs is launched for the first time.
On the next run, a warning shows up about `ido-ubiquitous` being deprecated, and most `cider` commands disappear/stop working.
I ended up creating [my own config](https://github.com/divs1210/.emacs.d) to mimic yours, but would be great to have this working again.
Thanks!

**Comment by vedang** [comment]
I'll fix this ASAP. Closing in favor of #5
